# calibration_config.yaml

image:
  name: "calibration-service-calibration-service"
  tag: "latest"

restart_policy:
  name: "on-failure"
  max_retries: 5

env_vars:
  EMAIL_SENDER: "${CALIB_EMAIL_SENDER}"
  EMAIL_PASSWORD: "${CALIB_EMAIL_PASSWORD}"

  MLFLOW_TRACKING_URI: "${CALIB_MLFLOW_TRACKING_URI}"
  MLFLOW_S3_ENDPOINT_URL: "${CALIB_MLFLOW_S3_ENDPOINT_URL}"
  AWS_ACCESS_KEY_ID: "${CALIB_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${CALIB_AWS_SECRET_ACCESS_KEY}"
  MLFLOW_EXPERIMENT_NAME: "${CALIB_MLFLOW_EXPERIMENT_NAME}"
  GIT_PYTHON_REFRESH: "${CALIB_GIT_PYTHON_REFRESH}"

  LOG_LEVEL: "${CALIB_LOG_LEVEL}"
  ARTIFACTS_PATH: "${CALIB_ARTIFACTS_PATH}"

  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  RABBITMQ_UI_PORT: "${RABBITMQ_UI_PORT}"

networks:
  - "tpp-network"