# dispatcher_config.yaml

image:
  name: "data-dispatcher-service-data-dispatcher-service"
  tag: "latest"

restart_policy:
  name: "on-failure"
  max_retries: 5

env_vars:
  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASS: "${RABBITMQ_PASS}"
  
  DATASET_SERVICE_ADDR: "${DISP_DATASET_SERVICE_ADDR}"
  BATCH_SIZE: "${DISP_BATCH_SIZE}"
  LOG_LEVEL: "${DISP_LOG_LEVEL}"
  UPPER_BOUND_CLIENTS: "${DISP_UPPER_BOUND_CLIENTS}"
  LOWER_BOUND_CLIENTS: "${DISP_LOWER_BOUND_CLIENTS}"

networks:
  - "tpp-network"